---
title: "Grants"

---

## Grants

As a tenure track professor, I have generated over $600,000 in external grants from the U.S. Department of Housing and Urban Development, Smart Transit, the Lincoln Institute of Land Policy, and the North Central Texas Council of Governments. Before beginning my academic career, I was a grant manager for the John Peter Smith Foundation--the non-profit arm of the Tarrant County, TX hospital network where I learned how to write and manage local, state, federal, and non-profit grants that had nothing to do with research. I have some *strong* opinions about grant writing as an academic and as a professional in the public sector. Hopefully, my experience can help others on their grant journey.

## Consulting

My grant writing experience and success can be useful for non-profits and governments looking for help developing and reviewing proposals, but more importantly, creating a grant strategy that leverages an organizations strengths while being mindful of the funding environment. Feel free to reach out to me if you have any questions about my grant consulting services